import { UserRole, RoleConfig } from '../types/role';

export const ROLE_CONFIGS: Record<UserRole, RoleConfig> = {
  community: {
    role: 'community',
    displayName: 'Citizen / Community',
    badgeColor: 'citizen',
    sidebarNav: [
      { id: 'home', label: 'Home Feed', path: '/', iconName: 'Home' },
      { id: 'explore', label: 'Explore Problems', path: '/explore', iconName: 'Compass' },
      { id: 'nearby', label: 'Nearby Issues', path: '/nearby', iconName: 'MapPin' },
      { id: 'report', label: 'Report a Problem', path: '/report', iconName: 'PlusCircle', highlight: true },
      { id: 'saved', label: 'Saved Challenges', path: '/saved', iconName: 'Bookmark' },
      { id: 'notifications', label: 'Notifications', path: '/notifications', iconName: 'Bell', badge: '3' },
      { id: 'profile', label: 'My Community Profile', path: '/profile', iconName: 'User' },
    ],
    mobileBottomNav: [
      { id: 'home', label: 'Home', path: '/', iconName: 'Home' },
      { id: 'explore', label: 'Explore', path: '/explore', iconName: 'Compass' },
      { id: 'report', label: 'Report', path: '/report', iconName: 'PlusCircle', highlight: true },
      { id: 'saved', label: 'Saved', path: '/saved', iconName: 'Bookmark' },
      { id: 'profile', label: 'Profile', path: '/profile', iconName: 'User' },
    ],
    primaryActionLabel: 'Report Local Problem',
    primaryActionPath: '/report',
  },
  citizen: {
    role: 'citizen',
    displayName: 'Citizen / Community',
    badgeColor: 'citizen',
    sidebarNav: [
      { id: 'home', label: 'Home Feed', path: '/', iconName: 'Home' },
      { id: 'explore', label: 'Explore Problems', path: '/explore', iconName: 'Compass' },
      { id: 'nearby', label: 'Nearby Issues', path: '/nearby', iconName: 'MapPin' },
      { id: 'report', label: 'Report a Problem', path: '/report', iconName: 'PlusCircle', highlight: true },
      { id: 'saved', label: 'Saved Challenges', path: '/saved', iconName: 'Bookmark' },
      { id: 'notifications', label: 'Notifications', path: '/notifications', iconName: 'Bell', badge: '3' },
      { id: 'profile', label: 'My Community Profile', path: '/profile', iconName: 'User' },
    ],
    mobileBottomNav: [
      { id: 'home', label: 'Home', path: '/', iconName: 'Home' },
      { id: 'explore', label: 'Explore', path: '/explore', iconName: 'Compass' },
      { id: 'report', label: 'Report', path: '/report', iconName: 'PlusCircle', highlight: true },
      { id: 'saved', label: 'Saved', path: '/saved', iconName: 'Bookmark' },
      { id: 'profile', label: 'Profile', path: '/profile', iconName: 'User' },
    ],
    primaryActionLabel: 'Report Local Problem',
    primaryActionPath: '/report',
  },
  student: {
    role: 'student',
    displayName: 'Student Innovator',
    badgeColor: 'student',
    sidebarNav: [
      { id: 'home', label: 'Home Feed', path: '/', iconName: 'Home' },
      { id: 'explore', label: 'Discover Challenges', path: '/explore', iconName: 'Compass' },
      { id: 'my-problems', label: 'My Problem Pods', path: '/my-problems', iconName: 'Lightbulb' },
      { id: 'my-teams', label: 'My Teams', path: '/teams', iconName: 'Users', badge: '2' },
      { id: 'projects', label: 'Projects & Prototypes', path: '/projects', iconName: 'FolderGit2' },
      { id: 'discover-people', label: 'Find Teammates', path: '/people', iconName: 'UserPlus' },
      { id: 'notifications', label: 'Notifications', path: '/notifications', iconName: 'Bell', badge: '5' },
      { id: 'profile', label: 'Student Portfolio', path: '/profile', iconName: 'User' },
    ],
    mobileBottomNav: [
      { id: 'home', label: 'Feed', path: '/', iconName: 'Home' },
      { id: 'explore', label: 'Explore', path: '/explore', iconName: 'Compass' },
      { id: 'create-team', label: 'Form Team', path: '/teams/create', iconName: 'PlusCircle', highlight: true },
      { id: 'teams', label: 'Teams', path: '/teams', iconName: 'Users' },
      { id: 'profile', label: 'Portfolio', path: '/profile', iconName: 'User' },
    ],
    primaryActionLabel: 'Propose Solution Pod',
    primaryActionPath: '/teams/create',
  },
  faculty: {
    role: 'faculty',
    displayName: 'Faculty Mentor',
    badgeColor: 'faculty',
    sidebarNav: [
      { id: 'home', label: 'Home Feed', path: '/', iconName: 'Home' },
      { id: 'recommended', label: 'Recommended Problems', path: '/explore', iconName: 'Sparkles' },
      { id: 'mentoring', label: 'My Mentoring Pods', path: '/mentoring', iconName: 'GraduationCap', badge: '4' },
      { id: 'student-teams', label: 'Supervised Teams', path: '/teams', iconName: 'Users' },
      { id: 'research', label: 'Research & Grants', path: '/research', iconName: 'BookOpen' },
      { id: 'impact', label: 'Academic Impact', path: '/impact', iconName: 'TrendingUp' },
      { id: 'profile', label: 'Academic Profile', path: '/profile', iconName: 'User' },
    ],
    mobileBottomNav: [
      { id: 'home', label: 'Feed', path: '/', iconName: 'Home' },
      { id: 'mentoring', label: 'Mentoring', path: '/mentoring', iconName: 'GraduationCap' },
      { id: 'guide', label: 'Guide Team', path: '/teams', iconName: 'PlusCircle', highlight: true },
      { id: 'teams', label: 'Teams', path: '/teams', iconName: 'Users' },
      { id: 'profile', label: 'Profile', path: '/profile', iconName: 'User' },
    ],
    primaryActionLabel: 'Adopt Problem for Mentorship',
    primaryActionPath: '/explore',
  },
  university: {
    role: 'university',
    displayName: 'University Portal',
    badgeColor: 'university',
    sidebarNav: [
      { id: 'home', label: 'Campus Feed', path: '/', iconName: 'Home' },
      { id: 'faculty-desk', label: 'Faculty Management', path: '/university/faculty', iconName: 'GraduationCap', highlight: true },
      { id: 'student-roster', label: 'Student Innovators', path: '/people', iconName: 'Users' },
      { id: 'teams', label: 'Campus Solution Teams', path: '/teams', iconName: 'Layers' },
      { id: 'industry-partners', label: 'Industry Partnerships', path: '/partnerships', iconName: 'Building2' },
      { id: 'research-patents', label: 'Patents & IP', path: '/research', iconName: 'Award' },
      { id: 'impact', label: 'Institutional Impact', path: '/impact', iconName: 'TrendingUp' },
    ],
    mobileBottomNav: [
      { id: 'home', label: 'Campus', path: '/', iconName: 'Home' },
      { id: 'faculty', label: 'Faculty', path: '/university/faculty', iconName: 'GraduationCap' },
      { id: 'add-faculty', label: 'Add Faculty', path: '/university/faculty', iconName: 'PlusCircle', highlight: true },
      { id: 'teams', label: 'Teams', path: '/teams', iconName: 'Layers' },
      { id: 'profile', label: 'Portal', path: '/profile', iconName: 'Building2' },
    ],
    primaryActionLabel: 'Onboard Faculty Mentor',
    primaryActionPath: '/university/faculty',
  },
  industry: {
    role: 'industry',
    displayName: 'Industry & CSR Partner',
    badgeColor: 'industry',
    sidebarNav: [
      { id: 'home', label: 'Innovation Feed', path: '/', iconName: 'Home' },
      { id: 'discover-problems', label: 'R&D Challenges', path: '/explore', iconName: 'Search' },
      { id: 'sponsored-bounties', label: 'Sponsor a Challenge', path: '/challenges/create', iconName: 'Award', highlight: true },
      { id: 'scouted-teams', label: 'Scouted Student Teams', path: '/teams', iconName: 'Users' },
      { id: 'pilots', label: 'Live Field Pilots', path: '/pilots', iconName: 'Rocket' },
      { id: 'impact', label: 'CSR Impact Reports', path: '/impact', iconName: 'TrendingUp' },
      { id: 'profile', label: 'Corporate Profile', path: '/profile', iconName: 'Building2' },
    ],
    mobileBottomNav: [
      { id: 'home', label: 'Feed', path: '/', iconName: 'Home' },
      { id: 'explore', label: 'Challenges', path: '/explore', iconName: 'Search' },
      { id: 'sponsor', label: 'Sponsor', path: '/challenges/create', iconName: 'PlusCircle', highlight: true },
      { id: 'teams', label: 'Teams', path: '/teams', iconName: 'Users' },
      { id: 'profile', label: 'Corporate', path: '/profile', iconName: 'Building2' },
    ],
    primaryActionLabel: 'Sponsor Real Challenge',
    primaryActionPath: '/challenges/create',
  },
  government: {
    role: 'government',
    displayName: 'Government / Nodal Desk',
    badgeColor: 'admin',
    sidebarNav: [
      { id: 'home', label: 'Civic Priority Feed', path: '/', iconName: 'Home' },
      { id: 'problems', label: 'Ward & District Issues', path: '/explore', iconName: 'MapPin' },
      { id: 'verification', label: 'Citizen Verification', path: '/verification', iconName: 'ShieldCheck' },
      { id: 'universities', label: 'Partner Colleges', path: '/universities', iconName: 'Landmark' },
      { id: 'solutions', label: 'Adopted Solutions', path: '/solutions', iconName: 'CheckCircle2' },
      { id: 'impact', label: 'State Impact Scorecard', path: '/impact', iconName: 'TrendingUp' },
      { id: 'reports', label: 'Executive Reports', path: '/reports', iconName: 'FileText' },
    ],
    mobileBottomNav: [
      { id: 'home', label: 'Civic', path: '/', iconName: 'Home' },
      { id: 'explore', label: 'Districts', path: '/explore', iconName: 'MapPin' },
      { id: 'verify', label: 'Verify', path: '/verification', iconName: 'PlusCircle', highlight: true },
      { id: 'solutions', label: 'Solutions', path: '/solutions', iconName: 'CheckCircle2' },
      { id: 'impact', label: 'Impact', path: '/impact', iconName: 'TrendingUp' },
    ],
    primaryActionLabel: 'Verify Ward Issues',
    primaryActionPath: '/explore',
  },
  ngo: {
    role: 'ngo',
    displayName: 'NGO / Non-Profit Org',
    badgeColor: 'citizen',
    sidebarNav: [
      { id: 'home', label: 'Grassroots Feed', path: '/', iconName: 'Home' },
      { id: 'community-issues', label: 'Community Problems', path: '/explore', iconName: 'Users' },
      { id: 'report-grassroots', label: 'Report Community Issue', path: '/report', iconName: 'PlusCircle', highlight: true },
      { id: 'partner-teams', label: 'Student Volunteers', path: '/teams', iconName: 'Layers' },
      { id: 'impact', label: 'Grassroots Impact', path: '/impact', iconName: 'TrendingUp' },
      { id: 'profile', label: 'Organization Profile', path: '/profile', iconName: 'Building2' },
    ],
    mobileBottomNav: [
      { id: 'home', label: 'Home', path: '/', iconName: 'Home' },
      { id: 'explore', label: 'Issues', path: '/explore', iconName: 'Users' },
      { id: 'report', label: 'Report', path: '/report', iconName: 'PlusCircle', highlight: true },
      { id: 'teams', label: 'Teams', path: '/teams', iconName: 'Layers' },
      { id: 'profile', label: 'Profile', path: '/profile', iconName: 'Building2' },
    ],
    primaryActionLabel: 'Submit Grassroots Problem',
    primaryActionPath: '/report',
  },
  admin: {
    role: 'admin',
    displayName: 'National Governance Desk',
    badgeColor: 'admin',
    sidebarNav: [
      { id: 'home', label: 'National Feed', path: '/', iconName: 'Home' },
      { id: 'governance', label: 'Institutional Approval', path: '/admin', iconName: 'ShieldCheck', highlight: true, badge: 'NEW' },
      { id: 'all-problems', label: 'Moderation Desk', path: '/explore', iconName: 'Compass' },
      { id: 'universities', label: 'Approved Universities', path: '/universities', iconName: 'Landmark' },
      { id: 'audit-logs', label: 'Security Audit Trail', path: '/admin', iconName: 'History' },
      { id: 'analytics', label: 'Platform Analytics', path: '/impact', iconName: 'BarChart3' },
    ],
    mobileBottomNav: [
      { id: 'home', label: 'Feed', path: '/', iconName: 'Home' },
      { id: 'admin-desk', label: 'Approval Desk', path: '/admin', iconName: 'ShieldCheck', highlight: true },
      { id: 'explore', label: 'Problems', path: '/explore', iconName: 'Compass' },
      { id: 'audit', label: 'Audit', path: '/admin', iconName: 'History' },
      { id: 'profile', label: 'Admin', path: '/profile', iconName: 'User' },
    ],
    primaryActionLabel: 'Review Pending Applications',
    primaryActionPath: '/admin',
  },
};

export const getRoleConfig = (role: string | null | undefined): RoleConfig => {
  if (!role) return ROLE_CONFIGS.student;
  const normalized = role.toLowerCase() as UserRole;
  return ROLE_CONFIGS[normalized] || ROLE_CONFIGS.student;
};
