import { Problem } from '../types/problem';

export const mapApiProblem = (p: any): Problem => ({
  id: p.id,
  title: p.title,
  description: p.description,
  category: p.category,
  state: p.state,
  district: p.district,
  location: p.location,
  impactLevel: p.impact_level,
  status: p.status,
  author: {
    id: p.created_by_id || p.author?.id,
    name: p.author?.full_name || p.author?.email || 'Citizen Reporter',
    role: p.author?.role || 'citizen',
    avatar: p.author?.avatar || p.author?.avatar_url || p.author_avatar || p.author?.profile_picture_url || '',
    location: `${p.district}, ${p.state}`,
    verified: p.is_verified,
  },
  images: p.media_urls || [],
  tags: p.tags || [],
  likesCount: p.likes_count || 0,
  commentsCount: p.comments_count || 0,
  sharesCount: p.shares_count || 0,
  savesCount: 0,
  activeTeamsCount: p.active_teams_count || 0,
  interestedUniversitiesCount: 0,
  industrySponsorsCount: 0,
  createdAt: p.created_at ? new Date(p.created_at).toLocaleDateString() : '',
  isLiked: p.is_liked,
  isSaved: p.is_saved,
  aiInsight: p.ai_insight,
});
